apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: mynginx
          image: nginx:1.18-alpine
          ports:
            - containerPort: 80
        - name: mybusybox
          image: busybox:1.34
          command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
          ports:
            - containerPort: 81