apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
    version: v2
spec:
  containers:
    - name: mypod
      image: nginx:1.18-alpine
      ports:
        - containerPort: 80
    - name: mypod
      image: nginx:1.18-alpine
      ports:
        - containerPort: 80