apiVersion: v1
kind: Pod
metadata:
  name: test-pod-by-file-yaml-create
  namespace: default
spec:
  containers:
    - image: nginx:latest
      imagePullPolicy: IfNotPresent
      name: my-container


