apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: prometheus
  labels:
    name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      hostPID: true # 控制 Pod 中容器是否可以共享宿主上的进程 ID 空间
      hostIPC: true # 控制 Pod 容器是否可共享宿主上的 IPC  (进程通信)
      hostNetwork: true # POD允许使用宿主机网络
      containers:
      - name: node-exporter
        image: bitnami/node-exporter:1.4.0
        ports:
        - containerPort: 9100
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext: # 安全上下文。
          privileged: true # 容器以特权方式允许（为了能够访问宿主机所有设备）
        args:
        - --path.procfs
        - /host/proc
        - --path.sysfs
        - /host/sys
        - --collector.filesystem.ignored-mount-points
        - '"^/(sys|proc|dev|host|etc)($|/)"'
        volumeMounts:
        - name: dev
          mountPath: /host/dev
        - name: proc
          mountPath: /host/proc
        - name: sys
          mountPath: /host/sys
        - name: rootfs
          mountPath: /rootfs
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      volumes: # 节点信息需要挂载到容器中
        - name: proc # /proc –CPU信息、内存信息、内核信息等
          hostPath:
            path: /proc
        - name: dev # /dev  ---存放与设备（包括外设）有关的文件
          hostPath:
            path: /dev
        - name: sys # /sys --硬件设备的驱动程序信息
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /