# 创建操作configmap的帐号
apiVersion: v1
kind: ServiceAccount # 集群内ServiceAccount 集群外 UserAccount
metadata:
  name: cmuser
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cmrole
rules:
  - apiGroups: [""]
    resources: ["configmaps"] # 资源
    verbs: ["get", "watch", "list"] # 操作权限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding  # 绑定
metadata:
  name: cmclusterrolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cmrole
subjects:
  - kind: ServiceAccount
    name: cmuser
    namespace: default